export const recordsTableHead = [
    { name: 'All Leads' },
    { name: 'Sold Leads' },
    { name: 'Scrubbed Leads' },
    { name: 'Lead by Verticals' },
    { name: 'Trashed Leads, Tools' },
];

export const leadsTableHead = [
    { name: 'Lead ID' },
    { name: 'Lead Name' },
    { name: 'Phone' },
    { name: 'Afflicate' },
    { name: 'Status' },
    { name: 'Created on' },
    { name: '$ Cost' },
    { name: '$ Revenue' },
];

export const dataBody = [
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
    {
        leadId: '00001',
        name: 'Noah Lewis',
        phoneNumber: '9165483248',
        afflicate: 'John Doe',
        status: 'Hot',
        createdAt: '08/12/2021',
        cost: 100,
        revenue: 0,
    },
];
