version: 0.2

phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export AWS_ACCOUNT_ID=984575983798
      - printenv > .env
      - echo "NEXT_PUBLIC_BACKEND_URL is $NEXT_PUBLIC_BACKEND_URL"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 984575983798.dkr.ecr.us-east-1.amazonaws.com
      - echo Logging in to Amazon EKS...
      - aws eks --region us-east-1 update-kubeconfig --name quik-influence-prod
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export IMAGE_REPO_NAME=quikinfluence-frontend
      - export VERSION_TAG=$(date '+%Y%m%d%H%M')
      - docker build -t $IMAGE_REPO_NAME:$VERSION_TAG .
      - docker tag $IMAGE_REPO_NAME:$VERSION_TAG $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$VERSION_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$VERSION_TAG 
      - echo Entered the deploy phase...
      - aws sts get-caller-identity
      - echo Deploying quiksession-frontend version VERSION_TAG to cluster
      - echo Entered the deploy phase...
      - echo Deploying quiksession-frontend version VERSION_TAG to cluster
      - sed -i "s/AWS_ECR_URI/$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com\/$IMAGE_REPO_NAME:$VERSION_TAG/g" k8.yml
      - grep image k8.yml
      - ./kubectl --kubeconfig='/root/.kube/config' config view
      - ./kubectl --kubeconfig='/root/.kube/config' apply -f k8.yml