import { EMAIL_REFEX, FREE_TEXT_REGEX } from '../regexConstants';
import { stateNames } from '../stateConstants';

export default [
    {
        number: 1,
        name: 'name',
        label: 'Campaign Name',
        errorMessage: 'Enter your campaign name',
        required: true,
        type: 'text',
        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 2,
        name: 'description',
        label: 'Campaign Description',
        errorMessage: 'Describe your campaign',
        required: true,
        type: 'text',
        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 3,
        name: 'campaignDate',
        label: 'Campaign Start Date',
        errorMessage: 'Enter your campaign start date',
        required: true,
        type: 'datetime-local',
        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 4,
        name: 'audience',
        label: 'Audience',
        errorMessage: 'Select atleast one audience',
        required: false,
        disabled: false,
        type: 'multi-select',
        options: [
            { label: 'Sports ', value: 'sports' },
            { label: 'Tv Shows', value: 'tvshows' },
            { label: 'Animals', value: 'animals' },
        ],
        pattern: FREE_TEXT_REGEX,
        extraLabel: '(add as many as apply)',
    },
    {
        name: 'gender',
        label: 'Gender ',
        errorMessage: 'Select your gender',
        required: true,
        disabled: false,
        isChild: true,
        type: 'select',
        options: [
            { label: 'Male', value: 'male' },
            { label: 'Female', value: 'female' },
            { label: 'Other', value: 'other' },],
        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'age',
        label: 'Age ',
        errorMessage: 'Select your age',
        required: true,
        disabled: false,
        isChild: true,
        type: 'select',
        options: [
            { label: '18-25', value: '18-25' },
            { label: '25-35', value: '25-35' },
            { label: '35-50', value: '35-50' },
            { label: '50-71', value: '50-71' },
            { label: '71-100', value: '71-100' },
        ],
        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'locations',
        label: 'Locations ',
        errorMessage: 'Add at least one location',
        required: true,
        disabled: false,
        isChild: true,
        type: 'multi-select',
        options: stateNames.reduce((acc: any, curr: any) => [...acc, { label: curr, value: curr }], []),

        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'leadTable',
        label: 'Display Results ',
        errorMessage: '',
        required: false,
        disabled: false,
        isChild: true,
        type: 'table',

        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 5,
        name: 'message',
        label: 'Email Message',
        errorMessage: 'enter the Email Message',
        required: false,
        type: 'rich_text_editor',
        pattern: FREE_TEXT_REGEX,
    },

    {
        number: 6,
        name: 'email',
        label: 'Send Test Ad',
        placeholder: 'Enter Email Address',
        errorMessage: 'enter email address',
        required: true,
        type: 'text',
        pattern: EMAIL_REFEX,
    },
    {
        number: 7,
        name: 'submit',
        label: 'Submit Campaign',
        extralabel: 'We will review your campaign and a correspond charges and approval decision to you',
        required: false,
        type: 'submit',
        pattern: FREE_TEXT_REGEX,
    },
];
