import { FREE_TEXT_REGEX } from '../regexConstants';
import { stateNames } from '../stateConstants';

export default [
    {
        number: 1,
        name: 'name',
        label: 'Campaign Name',
        errorMessage: 'Enter your campaign name',
        required: true,
        type: 'text',
        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 2,
        name: 'campaignDate',
        label: 'Campaign Start Date',
        errorMessage: 'Enter your campaign start date',
        required: true,
        type: 'date',
        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 3,
        name: 'audience',
        label: 'Audience',
        errorMessage: 'Select atleast one audience',
        required: false,
        disabled: false,
        type: 'multi-select',
        ranges: [],
        options: [
            { label: 'Sports ', value: 'sports' },
            { label: 'Tv Shows', value: 'tvshows' },
            { label: 'Animals', value: 'animals' },
        ],
        pattern: FREE_TEXT_REGEX,
        extraLabel: '(add as many as apply)',
    },
    {
        name: 'gender',
        label: 'Gender ',
        errorMessage: 'Select your gender',
        required: true,
        disabled: false,
        isChild: true,
        type: 'select',
        options: [
            { label: 'Male', value: 'male' },
            { label: 'Female', value: 'female' },
            { label: 'Other', value: 'other' },],
        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'age',
        label: 'Age ',
        errorMessage: 'Select your age',
        required: true,
        disabled: false,
        isChild: true,
        type: 'select',
        options: [
            { label: '18-25', value: '18-25' },
            { label: '25-35', value: '25-35' },
            { label: '35-50', value: '35-50' },
            { label: '50-71', value: '50-71' },
            { label: '71-100', value: '71-100' },
        ],
        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'locations',
        label: 'Locations ',
        errorMessage: 'Add at least one location age',
        required: true,
        disabled: false,
        isChild: true,
        type: 'multi-select',
        options: stateNames.reduce((acc: any, curr: any) => [...acc, { label: curr, value: curr }], []),

        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'leadTable',
        label: 'Display Results ',
        errorMessage: 'Add at least one location age',
        required: false,
        disabled: false,
        isChild: true,
        type: 'table',

        pattern: FREE_TEXT_REGEX,
    },
    {
        // number: 4,
        name: 'adSpend',
        label: 'Ad Spend',
        disabled: true,
        extraLabel: 'select daily spending for your campaign',
        errorMessage: 'Enter your ad spend',
        required: false,
        type: 'range-selector',
        pattern: FREE_TEXT_REGEX,
        ranges: [
            {
                title: 'How many SMS Messages would you like to send?',
                min: 1,
                max: 1000,
                isMoney: false,
                rangeProps: { maxW: '30rem' },
                rangeTitleProps: { fontSize: 'md', fontWeight: 'semibold' }
            },
        ]

    },
    {
        number: 4,
        name: 'message',
        label: 'SMS Message',
        errorMessage: 'enter the SMS Message',
        required: true,
        type: 'textarea',
        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'adImage',
        label: 'Add Ad Image',
        errorMessage: 'Add ad image',
        required: false,
        isChild: true,
        type: 'image-upload',
        pattern: FREE_TEXT_REGEX,
    },
    {
        name: 'adPreview',
        label: 'SMS Ad Preview',
        required: false,
        isChild: true,
        type: 'ad-preview',
        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 5,
        name: 'phone',
        label: 'Send Test Ad',
        placeholder: 'Enter Phone Number',
        errorMessage: 'enter phone number',
        required: true,
        type: 'text',
        pattern: FREE_TEXT_REGEX,
    },
    {
        number: 6,
        name: 'submit',
        label: 'Submit Campaign',
        extralabel: 'We will review your campaign and a correspond charges and approval decision to you',
        required: false,
        type: 'submit',
        pattern: FREE_TEXT_REGEX,
    },
];
