import { FREE_TEXT_REGEX } from '../regexConstants';

export default [
  {
    name: 'type',
    label: 'Choose your input type',
    errorMessage: 'Select type',
    required: true,
    disabled: false,
    isChild: true,
    type: 'select',
    options: [
      { label: 'Text', value: 'text' },
      { label: 'Select', value: 'select' },
      { label: 'Multi Select', value: 'multi-select' },
      { label: 'Checkbox', value: 'checkbox' },
      { label: 'Radio', value: 'radio' },
    ],
    pattern: FREE_TEXT_REGEX,
  },
  {
    name: 'name',
    label: 'Enter the name of your new input',
    errorMessage: 'Enter name',
    required: true,
    type: 'text',
    pattern: FREE_TEXT_REGEX,
  },
  {
    name: 'label',
    label: 'Please the label for your input',
    errorMessage: 'Enter label',
    required: true,
    type: 'text',
    pattern: FREE_TEXT_REGEX,
  },
  {
    name: 'pattern',
    label: 'Please choose a validation type',
    errorMessage: '',
    required: true,
    type: 'select',
    pattern: FREE_TEXT_REGEX,
    options: [
      { label: 'Free text', value: 'FREE_TEXT_REGEX' },
      { label: 'Credit card', value: 'CREDIT_CARD_REGEX' },
      { label: 'Email', value: 'EMAIL_REFEX' },
      { label: 'Phone Number', value: 'PHONE_NUMBER_REGEX' },
      { label: 'Full Name', value: 'FULL_NAME_REGEX' },
      { label: 'Number', value: 'NUMBER_REGEX' },
      { label: 'Link', value: 'URL_REGEX' },
    ],
  },
  {
    name: 'errorMessage',
    label: 'Please enter an error message',
    errorMessage: 'Enter Message',
    required: true,
    type: 'text',
    pattern: FREE_TEXT_REGEX,
  },
  {
    name: 'required',
    label: 'Should input be required?',
    errorMessage: 'Choose',
    required: false,
    type: 'checkbox',
    pattern: FREE_TEXT_REGEX,
  },
  {
    name: 'options',
    label: 'Please choose options',
    errorMessage: 'Choose options',
    required: false,
    type: 'text',
    pattern: FREE_TEXT_REGEX,
  },
];
