import {
  EMAIL_REFEX,
  FREE_TEXT_REGEX,
  PHONE_NUMBER_REGEX,
} from '../regexConstants';

export default [
  {
    name: 'firstName',
    label: 'First name',
    errorMessage: 'Enter your first name',
    required: true,
    value: 'amen',
    type: 'text',
    pattern: FREE_TEXT_REGEX,
    colSpan: 1,
  },
  {
    name: 'lastName',
    label: 'Last name',
    errorMessage: 'Enter your last name',
    required: true,
    type: 'text',
    pattern: FREE_TEXT_REGEX,
    colSpan: 1,
  },
  {
    name: 'gender',
    label: 'Gender',
    errorMessage: 'Enter your gender',
    required: true,
    type: 'text',
    pattern: FREE_TEXT_REGEX,
    colSpan: 2,
  },
  {
    name: 'address_line1',
    label: 'Address 1',
    type: 'text',
    placeholder: '000 place drive',
    errorMessage: 'Enter your address 1',
    required: true,
    pattern: FREE_TEXT_REGEX,
    colSpan: 2,
  },
  {
    name: 'address_line2',
    label: 'Address 2',
    type: 'text',
    placeholder: '000 place drive',
    errorMessage: '',
    required: false,
    pattern: FREE_TEXT_REGEX,
    colSpan: 2,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    errorMessage: 'Enter your phone',
    required: true,
    type: 'tel',
    pattern: PHONE_NUMBER_REGEX,
    colSpan: 1,
  },
  {
    name: 'dob',
    label: 'Date of birth',
    errorMessage: 'Enter your date of birth',
    required: true,
    type: 'date',
    pattern: PHONE_NUMBER_REGEX,
    colSpan: 1,
  },
  {
    name: 'city',
    label: 'City',
    type: 'text',
    errorMessage: 'Select country',
    required: true,
    pattern: FREE_TEXT_REGEX,
    colSpan: 1,
  },
  {
    name: 'address_zip',
    label: 'Zip Code',
    type: 'text',
    placeholder: '030303',
    errorMessage: 'Enter your zip code',
    required: true,
    pattern: FREE_TEXT_REGEX,
    colSpan: 1,
  },
  {
    name: 'address_state',
    label: 'State',
    type: 'select',
    errorMessage: 'Select a state',
    required: true,
    pattern: FREE_TEXT_REGEX,
    colSpan: 1,
  },
  {
    name: 'country',
    label: 'Country',
    type: 'select',
    errorMessage: 'Select your country',
    required: true,
    pattern: FREE_TEXT_REGEX,
    colSpan: 1,
  },
  {
    name: 'avatar',
    label: 'Profile picture',
    errorMessage: 'Upload profile picture',
    required: true,
    type: 'image-upload',
    pattern: FREE_TEXT_REGEX,
  },
];
