import Head from 'next/head';
import { InferGetStaticPropsType, GetStaticProps } from 'next';
import { axiosInstance } from 'utils/helpers';
import styles from '../styles/Home.module.css';
import {
  APP_NAME,
  HOME_PAGE_NAME,
  NAV_NAME,
} from 'utils/constants/pageDataConstants';
import NavBar from 'components/NavBar';
import EditableWrapper from 'components/EditableWrapper';
import { Box, Flex } from '@chakra-ui/react';
import Banner from 'components/HomePage/Banner';

type IpageContent = {
  banner: any;
  nav: any;
};

const Home = ({
  pageContent,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Quick Influence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar links={pageContent.nav[0].content.navLinks} />
        <Banner banner={pageContent.banner[0].content} />
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const banner = await axiosInstance.get(
    `/content?resource=${APP_NAME}&page=${HOME_PAGE_NAME}`
  );

  const nav = await axiosInstance.get(
    `/content?resource=${APP_NAME}&page=${NAV_NAME}`
  );

  const pageContent: IpageContent = {
    banner: banner.data.data,
    nav: nav.data.data,
  };

  return {
    props: {
      pageContent,
    },
    revalidate: 10,
  };
};

export default Home;
