import Head from 'next/head';
import { InferGetStaticPropsType, GetStaticProps } from 'next';
import NextLink from 'components/NextLink';
import { axiosInstance } from 'utils/helpers';
import styles from '../styles/Home.module.css';
import {
  APP_NAME,
  HOME_PAGE_NAME,
  NAV_NAME,
} from 'utils/constants/pageDataConstants';
import NavBar from 'components/NavBar';
import EditableWrapper from 'components/EditableWrapper';

import { Box, Flex } from '@chakra-ui/react';

type IpageContent = {
  banner: any;
  nav: any;
};

const Home = ({ pageContent }: { pageContent: IpageContent }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar links={pageContent.nav[0].content.navLinks} />
        <Box
          className={styles.section}
          as="section"
          h="calc(100vh - 173px)"
          w="100vw"
          background={`linear-gradient(to right, #000 50%, transparent), right / cover no-repeat url("/homepage.jpg")`}
        >
          <div className={styles.sectionFilter}></div>
          <Box maxW="container.lg"></Box>
        </Box>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const banner = await axiosInstance.get(
    `/content?resource=${APP_NAME}&page=${HOME_PAGE_NAME}`
  );

  const nav = await axiosInstance.get(
    `/content?resource=${APP_NAME}&page=${NAV_NAME}`
  );

  return {
    props: {
      pageContent: {
        banner: banner.data,
        nav: nav.data.data,
      },
    },
    revalidate: 10,
  };
};

export default Home;
