
export const FILTER_SEARCH_TYPE = {
    FUZZY_TEXT_SEARCH: 'FUZZY_TEXT_SEARCH',
    FULL_TEXT_SEARCH: 'FULL_TEXT_SEARCH',
    OPTIONS_SEARCH: 'OPTIONS_SEARCH',
    INTEGER_SEARCH: 'INTEGER_SEARCH',
    INTEGER_GREATER_THAN_SEARCH: 'INTEGER_GREATER_THAN_SEARCH',
    INTEGER_LESS_THAN_SEARCH: 'INTEGER_LESS_THAN_SEARCH',
    INTEGER_RANGE_SEARCH: 'INTEGER_RANGE_SEARCH',
}